workflows:
  my-workflow:
    environment:
      groups:
        - production
        - app_store_credentials
        - certificate_credentials
      vars:
        XCODE_WORKSPACE: "project.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "Release"
        BUNDLE_ID: "org.nhsrc.FacilitiesAssessment"
        APP_STORE_APP_ID: 1354891968 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
      node: 8.5.0
      xcode: 12.5
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Increment build number
        script: |
          #!/bin/sh
          set -e
          set -x
          cd $FCI_BUILD_DIR/ios
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Install npm dependencies
        script: |
          npm install
      - name: Configure for release
        script: make create-nhsrc-config
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --warn-only
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
