workflows:
  my-workflow:
    environment:
      groups:
        - production
        - app_store_credentials
        - certificate_credentials
      vars:
        XCODE_WORKSPACE: "project.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "Release"
        BUNDLE_ID: "org.nhsrc.FacilitiesAssessment"
        APP_STORE_APP_ID: 1354891968 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
      node: latest
      xcode: 12.5
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
            keychain initialize
      - name: Fetch signing files
        script: |
            app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
                keychain add-certificates
      - name: Install npm dependencies
        script: |
            npm install
      - name: Install CocoaPods dependencies
        script: |
            cd ios && pod install
      - name: Increment build number
        script: |
          cd ios
          agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
          --project "ios/FacilitiesAssessment.xcodeproj" \
          --scheme "Release"
    artifacts:
      - build/ios/ipa/*.ipa
