export default {
    LOGIN: "LOGIN",
    ENTER_USERNAME: "ENTER_USERNAME",
    ENTER_PASSWORD: "ENTER_PASSWORD",
    ALL_STATES: "ALL_STATES",
    SELECT_STATE: "SELECT_STATE",
    SELECT_DISTRICT: "SELECT_DISTRICT",
    SELECT_FACILITY_TYPE: "SELECT_FACILITY_TYPE",
    SELECT_FACILITY: "SELECT_FACILITY",
    FACILITY_SELECT: "FACILITY_SELECT",
    ALL_DEPARTMENTS: "ALL_DEPARTMENTS"
};