export default {
    "E19": "Post Natal Care",
    "E18": "Intranatal Care",
    "D10": "Legal & Statutory Requirements",
    "D11": "Human Resource Deployments",
    "D12": "Outsourced Services Monitoring",
    "E11": "Emergency & Disaster Management",
    "E10": "Intensive Care",
    "E13": "Blood Bank",
    "E12": "Diagnostic Services Quality",
    "E15": "Surgical Services",
    "E14": "Anesthesia",
    "E17": "Antenatal Care",
    "E16": "Management of Death",
    "E21": "Family Planning Care",
    "G7": "Quality Policy",
    "G6": "Assessment & Clinical Audits",
    "G5": "Process Improvement",
    "G4": "Standard Operating Procedures",
    "G3": "Quality Assurance",
    "G2": "Patient Satisfaction Survey",
    "G1": "Quality Team",
    "G8": "Quality Methods & Tools",
    "A1": "Curative Service Availability",
    "A3": "Diagnostics Availability",
    "A2": "RMNCH+A Services Availability",
    "A5": "Support Services Availability",
    "A4": "National Health Program Availability",
    "A6": "Community Health Needs",
    "C3": "Fire Safety",
    "C2": "Physical Safety",
    "C1": "Infrastructure & Layout",
    "E6": "Standard Treatment Guidelines",
    "E1": "Registration & Consultation",
    "C6": "Equipment Availability",
    "C5": "Drugs Availability",
    "C4": "Human Resource Availability",
    "E20": "Newborn & Child Health Care",
    "D8": "Community Participation",
    "E22": "Adolescent Health Care",
    "E23": "National Health Program Quality",
    "D9": "Financial Management",
    "F2": "Hand Hygiene",
    "F6": "Bio Medical Waste Management",
    "E5": "High Risk & Vulnerable Patients",
    "E4": "Nursing Care",
    "E7": "Safe Drug Administration",
    "E3": "Referral",
    "F1": "Infection Control Program",
    "E8": "Medical Record Management",
    "F3": "Personal Protection",
    "F4": "Disinfection & Sterilization",
    "F5": "Environmental Control",
    "E2": "Clinical  Assessment",
    "H2": "Efficiency Indicators",
    "H3": "Clinical Care Indicators",
    "H1": "Productivity Indicators",
    "H4": "Service Quality Indicators",
    "B4": "Patient Participation",
    "B5": "Free Services",
    "E9": "Discharge",
    "B1": "Information",
    "B2": "Access & Non Discrimination",
    "B3": "Privacy & Dignity",
    "D6": "Dietary Services",
    "D7": "Laundry Services",
    "D4": "Facility Upkeep",
    "D5": "Water and Power Supply",
    "D2": "Drug Storage & Inventory",
    "D3": "Safety & Comfort",
    "D1": "Equipment Maintenance"
}